
VM_syn_flood: VM_syn_flood.o  header.o
	gcc VM_syn_flood.o header.o -o VM_syn_flood

VM_syn_flood.o : VM_syn_flood.c
	gcc -c -Wall -g  VM_syn_flood.c 

header.o : header.c
	gcc -c -Wall -g header.c 

# connection:connection.c
# 	gcc connection.c -o connection
